### ISSUE TITLE
mitosis stdout/stderr output can't be synchronized

### ISSUE THREAD

**Issue by oli-cosmian** [Manishearth/mitosis#14]
Right now, all mitosis stdout/stderr output automatically shares its output with the parent process. This can lead to the usual amusing interleaved output, without being able to avoid the interleaving like it was possible in the single process case (locking the output).

I'd like to add some way to pipe the output manually, but wanted to open an issue beforehand to make sure that

a) this is even something that mitosis should solve
b) my design idea is going in the right direction

I propose to keep the `spawn` API just as it is right now, but also add a `builder` scheme similar to how `std::thread` has the `Builder` for configuring thread names and stack size.

To start out with, this API would only offer a way to spawn the process and to set the stdout/stderr capture mode just how it can be done with `Command`, exposing the stdout/stderr handles via the `JoinHandle`

**Comment by Manishearth** [comment]
A builder sounds nice especially since we can then add APIs that let you do custom spawning (for sandboxing etc)
