### ISSUE TITLE
Allow the use inside `#[test]`s

### ISSUE THREAD

**Issue by oli-cosmian** [Manishearth/mitosis#8]
Since we can't instrument the test binary's `main` function (yet), I think it would be possible to add an `init_test(name: &'static str)` function that users can call at the beginning of their test that uses `spawn` inside (usually because `spawn` is used inside a function imported from the library being tested). This `init_test` would then note the `name` in a global static that `spawn` reads from and uses as the first argument to the binary.

Furthermore we'd need to make the `--mitosis-content-process-id` argument be an environment variable in that case because the test binary would error due to the unknown argument.
Is there any particular reason this is not already an environment variable that is immediately cleared upon being read in `init`?

**Comment by Manishearth** [comment]
I'm open to making it an environment variable. I'm not quite clear on how the test stuff would work.

**Comment by oli-cosmian** [comment]
Basically my idea is to only annotate tests that use it. So if you have

```rust
// does some `mitosis` inside
fn foo() {}

#[test]
fn a() {}

#[test]
fn b() {
    mitosis::init_test("module::path::b");
    foo();
}
```

then when `foo` calls `spawn`, it fetches the "module::path::b" found in a global variable and calls the binary with that string as an argument. Thus only the test in question is run, and since it immediately finds the `mitosis::init_test` before doing any logic beyond the test harness, it should work just like if you added `mitosis::init` in the `main` function of a binary.

I'll cook up a PR for the env stuff, and a second one for the test stuff to show how I think it should work (+ tests showing that it does work (hopefully))

**Comment by Manishearth** [comment]
That's not going to work well, though, since it's going to first setup the
rust test harness stuff, so your process is going to end up doing more work.

**Comment by oli-cosmian** [comment]
> so your process is going to end up doing more work.

yea, that's ok, we're not spawning them by the thousands. And it's better to be slow during testing than not working at all

**Comment by Manishearth** [comment]
Sounds good, feel free to make these PRs, make sure you caveat the testing
API stuff
